language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - CODER_REPO='git://drupalcode.org/project/coder.git'
    - CODER_VERSION='7.x-2.2'

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

install:

  # Create a database for our Drupal site.
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Codesniffer.
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

  # Build Codebase
  - cd ../
  - mkdir profiles
  - mv drupress profiles/drupress
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch.
  - cd drupal
  - drush make --yes profiles/drupress/drupal-org-core.make --prepare-install
  - drush make --yes profiles/drupress/drupal-org.make --no-core --contrib-destination=profiles/drupress
  - mkdir sites/default/private
  - mkdir sites/default/private/files
  - mkdir sites/default/private/temp
  - cd ../

  # Verify that all the .make files will work on Drupal.org.
  - drush verify-makefile drupal/profiles/drupress/drupal-org.make
  - find drupal/profiles/drupress/modules -name \*.make -print0 | xargs -0 -n1 drush verify-makefile

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Clone Coder module for later.
  - git clone --branch $CODER_VERSION $CODER_REPO drupal/sites/all/modules/coder

before_script:

  - cd drupal/
  - drush si drupress --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="drupress" --yes
  - drush dis -y dblog
  - drush vset -y file_private_path "sites/default/private/files"
  - drush vset -y file_temporary_path "sites/default/private/temp"
  - cd ../drupal

  # Start the server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - SERVER_PID=$!
  - sleep 3

script:

  - phpcs --report=full --extensions=module,profile,inc,install --standard=sites/all/modules/coder/coder_sniffer/Drupal/ruleset.xml profiles/drupress/modules/contrib/drupress_support

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

notifications:
  email:
    recipients:
      - me@cafuego.net
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#cc-weaveweb"
    on_success: always
    on_failure: always
